# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62b7931627ce4c94fdfc5e27feda9e9c63421065b5f7557f9712d3013682193f1108b4b6bd13c84ed02bb0b108b3018f5a0a2ee0455ccf70067be2f3ee522274

test:
  secret_key_base: 0c8bdc50f648f18c6b9c70695cba5cf627c11d172beb6a71bafa306d3079d6ef52e6758a5284422514acf7dc228645e8512f38ae2824d1ab53d83bb8031ef7f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
